### ISSUE TITLE
Error during agent installation on Debian 10.3

### ISSUE THREAD

**Issue by svbackend** [deworkerpro/demo-auction-jenkins#1]
Hello, I tried to execute `make server` command but it fails during jenkins agent1 installation on Debian 10.3

The error I've got:

```
"The following packages have unmet dependencies:", " libc6-dev : Breaks: libgcc-8-dev (< 8.4.0-2~) but 8.3.0-6 is to be installed"
```

After some research I fixed it using `apt install gcc-8-base`

So I added this command to playbook, now it looks like this:

```
---
-   name: Add OpenJDK repository
    apt_repository:
        repo: 'deb http://ftp.us.debian.org/debian sid main'
        state: present
        filename: openjdk
        update_cache: yes

-   name: Install OpenJDK Dependencies <<<< NEW TASK
    apt:
        name:
            - gcc-8-base
        state: present
        update_cache: yes

-   name: Install OpenJDK
    apt:
        name:
            - openjdk-8-jre
        state: present
        update_cache: yes
```
